In [1]:
import pandas as pd
df = pd.read_csv("feature_transform_assignment2.csv")
x=df.copy()
x1=df.copy()
x2=df.copy()
x3=df.copy()
x4=df.copy()
x5=df.copy()
x6=df.copy()
x7=df.copy()
x8=df.copy()
x9=df.copy()
x10=df.copy()
x11=df.copy()
x12=df.copy()


# Normalization



# sklearn

In [2]:
from sklearn.preprocessing import MinMaxScaler

min_maxsclr=MinMaxScaler()
x=min_maxsclr.fit_transform(x)
x

array([[0.2],
       [0.1],
       [0.3],
       [0.4],
       [0.2],
       [0.6],
       [1. ],
       [0. ],
       [0.1]])

# manual

In [3]:
min1=x1.min()
max1=x1.max()

for col in x1:
    c2=x1[col]
    
    for i in range(len(c2)):
        a=c2[i]
        b=a-min1
        d=max1-min1
        e=b/d
        c2[i]=e
        
    x1[col]=c2
    
print(x1)

   price
0    0.2
1    0.1
2    0.3
3    0.4
4    0.2
5    0.6
6    1.0
7    0.0
8    0.1


# Standardization

# sklearn

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x2=scaler.fit_transform(x2)
x2

array([[-0.41635614],
       [-0.75701116],
       [-0.07570112],
       [ 0.26495391],
       [-0.41635614],
       [ 0.94626396],
       [ 2.30888405],
       [-1.09766619],
       [-0.75701116]])

# Manual

In [5]:
import math
m=x3.mean()

for col in x3:
    c2=x3[col]
    s=0
    
    for i in range(len(c2)):
        a=c2[i]
        
        a=a-m
        a=a*a
        
        s=s+a
    s=s/len(c2)
    
    std=math.sqrt(s)
    
    for i in range(len(c2)):
        a=c2[i]
        c2[i]=(a-m)/std
        
    x3=c2
    
print(x3)

0   -0.416356
1   -0.757011
2   -0.075701
3    0.264954
4   -0.416356
5    0.946264
6    2.308884
7   -1.097666
8   -0.757011
Name: price, dtype: float64


# Log Transformation

# sklearn

In [6]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log10)
x4=transformer.transform(x4)
x4

price
0  2.041393
1  2.021189
2  2.060698
3  2.079181
4  2.041393
5  2.113943
6  2.176091
7  2.000000
8  2.021189

In [7]:
import numpy as np
x5['natural_log'] = np.log10(x5['price']) 
print(x5)

   price  natural_log
0    110     2.041393
1    105     2.021189
2    115     2.060698
3    120     2.079181
4    110     2.041393
5    130     2.113943
6    150     2.176091
7    100     2.000000
8    105     2.021189


# manual

In [8]:
import numpy as np
for col in x6:
    
    for i in range(len(x6[col])):
        c1=x6[col]
        a=(c1[i])
        a=np.log10(c1[i])
        (c1[i])=a
        
    x6[col]=c1
    
print(x6)
        
       


      price
0  2.041393
1  2.021189
2  2.060698
3  2.079181
4  2.041393
5  2.113943
6  2.176091
7  2.000000
8  2.021189


# Robust Scaler

# sklearn

In [9]:
x77=x7
from sklearn.preprocessing import RobustScaler
RoSc=RobustScaler()
robust_df = RoSc.fit_transform(x7)
x7=robust_df 
x7

array([[ 0.        ],
       [-0.33333333],
       [ 0.33333333],
       [ 0.66666667],
       [ 0.        ],
       [ 1.33333333],
       [ 2.66666667],
       [-0.66666667],
       [-0.33333333]])

# Manual

In [18]:
x8

Median=x8['price'].quantile(q=0.5)
twenty_fifth_percentile=x8['price'].quantile(q=0.25)
Seventy_fifth_percentile=x8['price'].quantile(q=0.75)

for col in x8:
    c2=x8[col]
    
    for i in range(len(c2)):
        a=c2[i]
        a=a-Median
        diff=Seventy_fifth_percentile-twenty_fifth_percentile
        x_scale=a/diff
        c2[i]=x_scale
    x8[col]=c2
print(x8)

      price
0  0.000000
1 -0.333333
2  0.333333
3  0.666667
4  0.000000
5  1.333333
6  2.666667
7 -0.666667
8 -0.333333


# Max Absolute Scaler

# sklearn

In [23]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()

model = scaler .fit(x9)
model
x9=model.transform(x9)

x9

array([[0.73333333],
       [0.7       ],
       [0.76666667],
       [0.8       ],
       [0.73333333],
       [0.86666667],
       [1.        ],
       [0.66666667],
       [0.7       ]])

# Manual

In [35]:
for col in x11:
    c1=x11[col]
    m=c1.max()
    
    for i in range(len(c1)):
        
        a=c1[i]
        a=a/m
        
        c1[i]=a
    
    x11[col]=c1
    
print(x11)
        

      price
0  0.733333
1  0.700000
2  0.766667
3  0.800000
4  0.733333
5  0.866667
6  1.000000
7  0.666667
8  0.700000
